<?php

namespace App\Support;

use App\Models\Room;
use Carbon\CarbonImmutable;

/**
 * Banque de questions intégrée.
 *
 * Syntaxe des modèles :
 * - {name}            → prénom du joueur visé (celui dont on devine la réponse)
 * - {fou|folle}       → accord selon le sexe du joueur visé (masculin|féminin)
 * - {t:fier|fière}    → idem, forme explicite
 * - {p:beau|belle}    → accord selon le sexe du/de la PARTENAIRE (celui qui devine)
 */
class Questions
{
    public const PACKS = [
        'decouverte' => [
            'label' => 'Découverte',
            'icon' => 'search',
            'desc'  => 'Apprendre à se connaître (encore mieux)',
            'questions' => [
                'Quel est le plat préféré de {name} ?',
                'Quelle est la plus grande peur de {name} ?',
                'Quel pays {name} rêve de visiter ?',
                'Quel est le film préféré de {name} ?',
                'Quelle habitude {name} aimerait perdre ?',
                'Quel était le métier de rêve de {name} enfant ?',
                'Quelle chanson {name} écoute en boucle en ce moment ?',
                "Qu'est-ce qui met {name} de mauvaise humeur à coup sûr ?",
                'Quel super-pouvoir {name} choisirait ?',
                "Quel est le souvenir d'enfance préféré de {name} ?",
                'De quoi {name} est le plus {fier|fière} dans sa vie ?',
                'Si {name} gagnait au loto, quel serait son premier achat ?',
                'Quelle est la saison préférée de {name} ?',
                'Quel dessert fait complètement craquer {name} ?',
                'Quelle célébrité {name} inviterait à dîner ?',
                'Quel est le pire métier imaginable pour {name} ?',
                'Que fait {name} en premier le matin ?',
                'Quelle appli {name} utilise le plus sur son téléphone ?',
                'Thé, café ou chocolat chaud pour {name} ?',
                'Quel animal représenterait le mieux {name} ?',
                'Dans quelle matière {name} était {bon|bonne} à l\'école ?',
                'Quel bruit ou tic agace {name} plus que tout ?',
                "Plutôt soirée canapé ou sortie improvisée pour {name} ?",
                'Quel talent {name} aimerait apprendre du jour au lendemain ?',
                "Quelle est la couleur préférée de {name} ?",
                "Quel super-héros {name} préfère ?",
                "Plutôt pizza ou sushi pour {name} ?",
                "Quelle fête de l'année {name} attend le plus ?",
                "Quel est le jeu vidéo ou de société préféré de {name} ?",
                "Quelle matière {name} détestait à l'école ?",
                "Quel a été le premier concert de {name} ?",
                "Quelle est la boisson préférée de {name} en soirée ?",
                "Quel livre a marqué {name} ?",
                "Quelle langue {name} aimerait parler couramment ?",
                "Combien d'heures de sommeil il faut à {name} pour être de bonne humeur ?",
                "Quel est le cauchemar récurrent de {name} ?",
                "Quelle est l'odeur préférée de {name} ?",
                "Plutôt douche du matin ou du soir pour {name} ?",
                "Quel objet {name} emporte partout ?",
                "Quelle émission de télé {name} regardait enfant ?",
                "Quel âge avait {name} à son premier baiser ?",
                "Dans quelle ville {name} se verrait bien poser ses valises ?",
                "Quel est le plus grand regret de {name} ?",
                "Que collectionnait {name} enfant ?",
                "Quel est le plat que {name} ne mangera jamais ?",
                "Plutôt voiture, moto ou vélo pour {name} ?",
                "Quelle appli {name} devrait désinstaller pour son bien ?",
                "Quel talent des autres rend {name} {jaloux|jalouse} ?",
                "Quelle est la pire note que {name} a eue à l'école ?",
                "Quel surnom portait {name} enfant ?",
                "Quel film fait pleurer {name} à coup sûr ?",
                "Quelle chanson {name} connaît par cœur ?",
                "Quel personnage historique fascine {name} ?",
                "Quelle est la plus grande phobie de {name} ?",
                "Plutôt camping sauvage ou hôtel 5 étoiles pour {name} ?",
                "Quel sport {name} adore regarder (même sans le pratiquer) ?",
                "Quel a été le premier achat de {name} avec son propre argent ?",
                "Quelle habitude alimentaire bizarre a {name} ?",
                "Quel emoji résume la personnalité de {name} ?",
                "Quelle saison rend {name} mélancolique ?",
                "Quel métier {name} ne pourrait jamais faire ?",
                "Quel pays {name} n'a aucune envie de visiter ?",
                "Quelle est l'heure idéale de coucher pour {name} ?",
                "Quel est le petit-déjeuner idéal de {name} ?",
                "Quelle célébrité agace {name} au plus haut point ?",
                "Quel cadeau ferait le plus plaisir à {name} là, tout de suite ?",
                "À quoi ressemble la journée parfaite de {name}, du réveil au coucher ?",
                "Quelle compétence inutile {name} maîtrise parfaitement ?",
                "Plutôt montagnes russes ou grande roue pour {name} ?",
                "Quel est le pire voyage de {name} ?",
                "Pour quelle chose {name} est toujours en retard ?",
                "Quel plat de son enfance manque le plus à {name} ?",
                "Quelle est la première chose que {name} regarde chez quelqu'un ?",
                "Quel genre de musique {name} n'écoute jamais ?",
                "Quelle corvée {name} déteste le plus ?",
                "Quel animal {name} ne toucherait pour rien au monde ?",
                "Quelle est la plus belle ville que {name} ait visitée ?",
                "Quel est le rêve le plus fou de {name} ?",
                "Plutôt livre papier, liseuse ou podcast pour {name} ?",
                "Dans quelle décennie {name} aurait aimé vivre ?",
                "Quel plat {name} pourrait cuisiner les yeux fermés ?",
                "Dans quelle matière {name} aurait aimé être {meilleur|meilleure} ?",
                "Quel est l'endroit le plus insolite où {name} s'est {endormi|endormie} ?",
                "Quel achat impulsif {name} a le plus regretté ?",
                "Quelle série {name} a abandonnée en cours de route ?",
                "Quel légume {name} refuse de manger ?",
                "Quelle appli {name} ouvre en premier le matin ?",
                "Quel est le contact le plus étonnant du téléphone de {name} ?",
                "Quel jour de la semaine {name} préfère ?",
                "Quel mot {name} dit beaucoup trop souvent ?",
                "Quelle météo met {name} de bonne humeur ?",
                "Quelle chose {name} n'a jamais osé faire ?",
                "Plutôt fromage ou dessert pour {name} ?",
                "Quel objet de son enfance {name} a gardé ?",
                "Quel prénom {name} aurait aimé porter ?",
                "Quelle nouvelle compétence {name} veut apprendre cette année ?",
                "De quel record insolite {name} pourrait se vanter ?",
                "Quel bruit {name} trouve le plus satisfaisant ?",
                "Plutôt lever de soleil ou coucher de soleil pour {name} ?",
                "Quelle chose fait pleurer {name} de rire à chaque fois ?",
            ],
        ],
        'fun' => [
            'label' => 'Fun',
            'icon' => 'smile',
            'desc'  => 'Pour rigoler un bon coup',
            'questions' => [
                'Quel emoji {name} utilise le plus ?',
                'Quelle chanson {name} chante sous la douche ?',
                'Quel est le talent caché (ou complètement inutile) de {name} ?',
                'Si {name} était un personnage de dessin animé, lequel ?',
                'Quelle est la pire mode que {name} a suivie ?',
                'Quel plat {name} rate à chaque fois ?',
                "Combien de temps {name} survivrait dans un film d'horreur ?",
                'Quelle phrase {name} répète tout le temps ?',
                'Si {name} devait manger un seul plat toute sa vie, lequel ?',
                'Quelle bêtise {name} faisait enfant ?',
                'Si {name} était un objet de la maison, lequel ?',
                'Quel serait le nom de scène de {name} en star de la chanson ?',
                'Quelle série {name} pourrait regarder en entier pour la troisième fois ?',
                "Que ferait {name} en premier en cas d'apocalypse zombie ?",
                'Quel est le pire cadeau que {name} a déjà reçu ?',
                'Dans quel domaine {name} se croit très {fort|forte}... alors que pas du tout ?',
                'Quel âge mental a réellement {name} ?',
                "Si {name} pouvait échanger sa vie avec quelqu'un pour une journée, avec qui ?",
                'Quel est le pire réflexe de {name} quand son téléphone sonne trop tôt ?',
                'Quelle victoire complètement inutile rendrait {name} très {fier|fière} ?',
                '{name} est {perdu|perdue} sur une île déserte : quel objet inutile emporte-t-{il|elle} ?',
                'Quelle danse {name} sort quand {il|elle} croit que personne ne regarde ?',
                'Si la vie de {name} était une télé-réalité, quel en serait le titre ?',
                'Quel mensonge {name} sort le plus souvent (« j\'arrive dans 5 minutes »...) ?',
                "Si {name} était un fromage, lequel ?",
                "Quel serait le slogan de {name} sur une affiche ?",
                "Quelle chanson honteuse {name} adore en secret ?",
                "Si {name} gagnait un prix, ce serait pour quoi ?",
                "Quel animal a le même caractère que {name} au réveil ?",
                "Quelle est la pire coupe de cheveux que {name} a portée ?",
                "Si {name} était un condiment, lequel ?",
                "Quel super-pouvoir inutile irait bien à {name} ?",
                "Combien de temps {name} tiendrait sans téléphone ?",
                "Quelle télé-réalité {name} pourrait gagner ?",
                "Si {name} était prof, ce serait de quelle matière ?",
                "Quel plat {name} commande toujours au resto ?",
                "Quelle est la danse signature de {name} en soirée ?",
                "Si {name} devait fuir le pays, ce serait pour quelle raison absurde ?",
                "Quel objet {name} pourrait vendre à n'importe qui ?",
                "Quelle phrase {name} sort quand {il|elle} a tort ?",
                "Quel emoji {name} utilise complètement de travers ?",
                "Quel serait le titre de l'autobiographie de {name} ?",
                "Si {name} était un personnage de sitcom, lequel ?",
                "Quelle bêtise {name} referait sans hésiter ?",
                "Quel est le pire jeu de mots de {name} ?",
                "Combien de temps {name} met VRAIMENT à se préparer ?",
                "Si {name} était un bruit, lequel ?",
                "Quelle célébrité {name} imite le mieux ?",
                "Quelle chose {name} fait en cachette ?",
                "Si {name} était un moyen de transport, lequel ?",
                "Quel aliment {name} défend contre l'avis général ?",
                "Quelle appli {name} ouvrirait pendant l'apocalypse ?",
                "Avec quel talent {name} gagnerait un radio-crochet ?",
                "Si la maison brûlait, quel objet inutile {name} sauverait ?",
                "Quelle excuse bidon {name} utilise le plus ?",
                "Quelle partie du corps {name} trouve la plus drôle ?",
                "Si {name} était un jour férié, lequel ?",
                "Quelle chanson {name} massacre au karaoké ?",
                "Quel serait le nom du groupe de rock de {name} ?",
                "Quelle habitude de {name} ferait un bon sketch ?",
                "Marcher pieds nus sur un Lego ou se cogner le petit orteil : le pire pour {name} ?",
                "Quel est le pire pyjama de {name} ?",
                "Si {name} était un ustensile de cuisine, lequel ?",
                "Quelle est la peur la plus absurde de {name} ?",
                "Quel mensonge d'enfant {name} a maintenu le plus longtemps ?",
                "Quel est le record de sieste de {name} ?",
                "Si {name} était célèbre pour un jour, que ferait-{il|elle} ?",
                "Quelle pub {name} chante encore des années après ?",
                "Quel plat raté {name} a déjà servi avec fierté ?",
                "Quelle est la pire idée de business de {name} ?",
                "Combien de photos ratées avant LA bonne photo de profil pour {name} ?",
                "Si {name} avait une baguette magique une heure, que ferait-{il|elle} ?",
                "Quel dessin animé {name} regarde encore sans complexe ?",
                "Quel est le pire conseil que {name} a donné avec assurance ?",
                "Quelle odeur {name} adore alors que tout le monde la déteste ?",
                "Si {name} était un magasin, lequel ?",
                "Quelle phrase de drague toute nulle {name} pourrait sortir ?",
                "Quel objet du quotidien {name} a déjà cassé bêtement ?",
                "Quel serait le pire métier pour {name} vu son caractère ?",
                "Quelle chose {name} cherche sur internet en cachette ?",
                "À Koh-Lanta, {name} serait {éliminé|éliminée} pour quoi ?",
                "Quel fruit ou légume ressemble le plus à {name} au réveil ?",
                "Quelle exagération {name} raconte à chaque fois ?",
                "Quel geste du quotidien {name} rate une fois sur deux ?",
                "Si {name} avait une musique d'entrée, laquelle ?",
                "Quelle règle absurde {name} instaurerait en devenant {président|présidente} ?",
                "Quel est le pire achat en ligne de {name} ?",
                "Que fait {name} au téléphone sans s'en rendre compte ?",
                "Si {name} était une appli, laquelle ?",
                "Quel plat mystère {name} pourrait inventer à 3 h du matin ?",
                "Quel est le surnom le plus ridicule qu'on ait donné à {name} ?",
                "Quelle situation fait rire {name} alors qu'il ne faudrait vraiment pas ?",
                "Si {name} était un meme, lequel ?",
                "Quel sport olympique {name} pense secrètement pouvoir faire ?",
                "Quelle chanson {name} met pour se donner du courage ?",
                "Quel objet {name} a perdu le plus de fois ?",
                "Si {name} écrivait un livre de cuisine, quel serait le plat vedette ?",
                "Quelle réaction a {name} devant une araignée ?",
                "Quel âge mental a {name} devant un trampoline ?",
                "Quelle voix bizarre {name} prend avec les animaux ?",
            ],
        ],
        'romantique' => [
            'label' => 'Romantique',
            'icon' => 'heart',
            'desc'  => 'Souvenirs et petits mots doux',
            'questions' => [
                'Quel a été le moment préféré de {name} dans votre histoire ?',
                'Quelle chanson fait penser {name} à vous deux ?',
                'Quelle a été la première impression de {name} en te rencontrant ?',
                'Quel geste tendre {name} préfère recevoir ?',
                'De quelle destination de voyage en amoureux rêve {name} ?',
                "Quel surnom {name} préfère qu'on lui donne ?",
                'Quel moment de votre relation {name} aimerait revivre ?',
                "Qu'est-ce qui fait le plus craquer {name} chez toi ?",
                "Quelle est la déclaration d'amour idéale pour {name} ?",
                'Quel petit détail de toi {name} adore ?',
                "Pour {name}, c'est quoi la soirée en amoureux parfaite ?",
                'Quel projet à deux fait le plus rêver {name} ?',
                'Quelle photo de vous deux {name} préfère ?',
                "Qu'est-ce que {name} admire le plus chez toi ?",
                'Quel est le plus beau cadeau que {name} ait reçu de toi ?',
                'Comment {name} imagine votre vie dans dix ans ?',
                'Quelle attention toute simple rend {name} {heureux|heureuse} à coup sûr ?',
                'Quel est le mot doux préféré de {name} ?',
                "Dans quel lieu {name} rêverait de t'embrasser ?",
                "Qu'est-ce qui manque le plus à {name} quand vous êtes loin l'un de l'autre ?",
                'À quel moment {name} s\'est {dit|dite} pour la première fois : « c\'est {p:lui|elle} » ?',
                'Quelle chose {name} aimerait te dire plus souvent ?',
                'Quel rituel à deux {name} chérit le plus ?',
                "Qu'est-ce que {name} prépare secrètement pour te faire plaisir ?",
                "Quel détail de votre première rencontre {name} n'a jamais oublié ?",
                "Quelle chanson {name} voudrait pour votre prochain slow ?",
                "Quel message de toi {name} a relu plusieurs fois ?",
                "Quelle saison est la plus romantique pour {name} ?",
                "Quel serait le dîner en amoureux parfait selon {name} ?",
                "Quelle petite manie à toi {name} trouve adorable ?",
                "Quel film d'amour fait fondre {name} ?",
                "Quelle ville {name} trouve la plus romantique ?",
                "Quel souvenir à deux {name} raconterait à vos petits-enfants ?",
                "Quel geste tu fais sans y penser et qui touche {name} ?",
                "Comment {name} décrirait votre couple en trois mots ?",
                "Quelle date {name} n'oubliera jamais ?",
                "Quel cadeau fait main toucherait le plus {name} ?",
                "Où {name} rêverait de se réveiller à tes côtés ?",
                "Quelle chanson {name} t'enverrait pour dire « tu me manques » ?",
                "Quel serait le week-end surprise idéal pour {name} ?",
                "Qu'est-ce que {name} préfère dans vos appels ou vos messages ?",
                "À quel moment de la journée {name} pense le plus à toi ?",
                "Quelle photo de toi {name} garde précieusement ?",
                "Quel est le plus beau compliment que {name} t'ait fait ?",
                "Quelle promesse {name} aimerait te faire ?",
                "Quel endroit vous appartient un peu, selon {name} ?",
                "Quelle habitude à deux {name} attend avec impatience ?",
                "Quel plat {name} aimerait cuisiner pour toi ?",
                "De quelle qualité de votre couple {name} est le plus {fier|fière} ?",
                "Quel surnom {name} te donne dans sa tête ?",
                "Quelle attention à distance touche le plus {name} ?",
                "Quel serait le voyage de noces de rêve de {name} ?",
                "Quelle chanson décrit votre histoire selon {name} ?",
                "Quel moment difficile vous a rapprochés, d'après {name} ?",
                "Qu'est-ce que {name} a appris de toi ?",
                "Quelle est la première chose que {name} fera en te retrouvant ?",
                "Quel serait le nom de votre futur animal de compagnie selon {name} ?",
                "Quelle tradition de couple {name} voudrait créer ?",
                "Quel est le rêve à deux le plus fou de {name} ?",
                "Quelle danse {name} aimerait apprendre avec toi ?",
                "Quel petit mot {name} aimerait trouver dans sa poche ?",
                "Quelle est la plus belle preuve d'amour que {name} ait reçue de toi ?",
                "Comment {name} imagine vos vieux jours ensemble ?",
                "Quel film {name} voudrait revoir {blotti|blottie} contre toi ?",
                "Quelle odeur fait immédiatement penser {name} à toi ?",
                "Quel talent à toi impressionne {name} ?",
                "Quelle chose {name} n'ose pas encore te demander ?",
                "Quel serait le pique-nique parfait selon {name} ?",
                "Quelle étoile, chanson ou fleur {name} t'associerait ?",
                "Quel moment de complicité {name} préfère dans votre quotidien ?",
                "Quelle lettre {name} aimerait recevoir de toi ?",
                "Quelle est la définition du bonheur à deux pour {name} ?",
                "Quel objet symbolise votre histoire pour {name} ?",
                "Quelle destination {name} associe à votre couple ?",
                "Quel fou rire à deux {name} n'oubliera jamais ?",
                "Quelle chanson {name} fredonne en pensant à toi ?",
                "Quel projet de maison fait rêver {name} ?",
                "Quelle fête {name} préférerait passer rien qu'avec toi ?",
                "Qu'est-ce qui a le plus {surpris|surprise} {name} chez toi ?",
                "Quel rituel du soir {name} aimerait partager avec toi ?",
                "Quelle qualité de ton cœur {name} admire en silence ?",
                "Quel serait votre tatouage de couple (même pour rire) selon {name} ?",
                "Quelle réplique de film d'amour {name} pourrait te dire ?",
                "Quel petit-déjeuner au lit ferait fondre {name} ?",
                "Quelle activité à deux {name} veut absolument tester ?",
                "À quel moment {name} a su que tu comptais vraiment ?",
                "Quelle chanson {name} mettrait dans une playlist rien que pour vous ?",
                "Main dans les cheveux ou bras autour des épaules : que préfère {name} ?",
                "Quelle surprise {name} rêverait que tu lui fasses ?",
                "Quel compliment {name} ne se lasse jamais d'entendre ?",
                "Quelle période de votre histoire {name} préfère jusqu'ici ?",
                "Quel détail de ton visage {name} préfère ?",
                "Quel objet à toi {name} aimerait garder près de {lui|elle} ?",
                "Quel serait le titre du film de votre histoire selon {name} ?",
                "Quelle promenade main dans la main ferait rêver {name} ?",
                "Quel mot doux {name} trouve le plus beau de la langue française ?",
                "Quelle attention {name} aimerait recevoir un jour de pluie ?",
                "Quel anniversaire (rencontre, premier baiser...) compte le plus pour {name} ?",
                "Que dirait {name} à son toi du passé, avant de te rencontrer ?",
                "Quel « je t'aime » {name} préfère : chuchoté, écrit ou crié ?",
            ],
        ],
        'coquin' => [
            'label' => 'Coquin',
            'icon' => 'flame',
            'desc'  => 'Séduction, charme et sous-entendus',
            'questions' => [
                'Quelle tenue te rend irrésistible aux yeux de {name} ?',
                "Quel compliment fait le plus d'effet à {name} ?",
                'Où {name} rêverait de passer une nuit avec toi ?',
                'Quel geste fait totalement craquer {name} ?',
                'Quelle partie de ton corps {name} préfère ?',
                "Quel serait le programme d'une soirée (très) rapprochée selon {name} ?",
                "Quel est le message le plus osé que {name} t'a déjà envoyé ?",
                'Quel parfum ou quelle odeur rend {name} {fou|folle} ?',
                "Slow sensuel ou regard qui en dit long : quelle est l'arme de séduction de {name} ?",
                'Quel souvenir à deux fait encore rougir {name} ?',
                'Quelle est la plus grande audace de {name} ?',
                'Massage ou câlin interminable : que préfère {name} ?',
                'Quel surnom secret {name} aimerait te donner ?',
                'Quel rendez-vous surprise ferait complètement chavirer {name} ?',
                "Lumière tamisée, bougies ou pénombre totale : l'ambiance préférée de {name} ?",
                "Quelle petite habitude à toi trouble {name} plus qu'{il|elle} ne l'avoue ?",
                'Quel est le fantasme de voyage en amoureux de {name} ?',
                'À quel moment {name} te trouve le plus {p:séduisant|séduisante} ?',
                'Quelle chanson mettrait {name} pour une soirée en tête-à-tête ?',
                'Quel est le baiser préféré de {name} ?',
                'Quel regard de toi {name} ne sait pas ignorer ?',
                'Quelle danse {name} rêverait de partager avec toi, collés-serrés ?',
                "Qu'est-ce que {name} remarque en premier quand tu t'habilles pour sortir ?",
                'Petit-déjeuner au lit ou grasse matinée câline : que choisit {name} ?',
                "Quel regard de {name} veut tout dire ?",
                "Quelle partie de son propre corps {name} assume le plus ?",
                "Quel vêtement {name} trouve le plus élégant sur toi ?",
                "Quelle heure de la journée inspire le plus {name} pour un câlin ?",
                "Quel parfum {name} mettrait pour te faire tourner la tête ?",
                "Baiser volé ou baiser attendu : que préfère {name} ?",
                "Quelle chanson donne envie à {name} de danser collé à toi ?",
                "Quel compliment {name} n'ose pas te faire en public ?",
                "Quel geste discret {name} utilise pour dire « viens près de moi » ?",
                "Quelle soirée à deux {name} referait volontiers ?",
                "Quel est votre rendez-vous le plus mémorable selon {name} ?",
                "Sur quelle partie du corps {name} préfère recevoir un baiser ?",
                "Quelle tenue à toi fait le plus d'effet à {name} ?",
                "Quel restaurant aux chandelles ferait craquer {name} ?",
                "Quel petit jeu de séduction {name} adore ?",
                "Quelle danse {name} n'oserait jamais... sauf avec toi ?",
                "Quel message de bonne nuit {name} préfère recevoir ?",
                "Quelle attitude chez toi {name} trouve la plus séduisante ?",
                "Quel moment de complicité fait battre le cœur de {name} plus vite ?",
                "Bain moussant ou douche rapide à deux : le choix de {name} ?",
                "Quelle tenue de soirée {name} aimerait te voir porter ?",
                "Quel emoji {name} t'enverrait pour dire « tu me plais » ?",
                "Quel souvenir de vacances fait sourire {name} d'un air complice ?",
                "Quel slow {name} choisirait pour un moment rien qu'à vous ?",
                "Quelle lumière préfère {name} pour une soirée en tête-à-tête ?",
                "Quel petit surnom {name} réserve aux moments tendres ?",
                "Quelle phrase de toi fait toujours son effet sur {name} ?",
                "Quel endroit public {name} trouve étrangement romantique ?",
                "Quel geste de ta part {name} attend en secret ?",
                "Quelle boisson {name} associerait à une soirée séduction ?",
                "Quel film {name} choisirait pour se blottir contre toi ?",
                "Quelle saison inspire le plus {name} pour les câlins ?",
                "Quel serait le dress code d'une soirée surprise selon {name} ?",
                "Quel jeu à deux {name} aimerait tenter (cartes, gages...) ?",
                "À quel moment de la journée {name} pense à toi... autrement ?",
                "Quelle attention inattendue ferait rougir {name} de plaisir ?",
                "Quel lieu de votre quotidien {name} trouve propice aux câlins ?",
                "Quelle mélodie met {name} d'humeur câline ?",
                "Quel compliment sur son corps {name} rêve d'entendre ?",
                "Quel rendez-vous mystère {name} accepterait les yeux fermés ?",
                "Cuisiner, danser ou masser : l'activité la plus sensuelle selon {name} ?",
                "Quel détail de ta voix trouble {name} ?",
                "Quelle escapade d'un soir ferait chavirer {name} ?",
                "Quel petit mot glissé dans sa poche ferait rougir {name} ?",
                "Quel moment {name} a trouvé le plus électrique entre vous ?",
                "Quelle façon de te dire bonjour {name} préfère ?",
                "Plage au coucher du soleil ou cheminée l'hiver : le cadre préféré de {name} ?",
                "Quelle petite audace {name} aimerait oser un jour ?",
                "Quel regard de toi déstabilise {name} à tous les coups ?",
                "Quelle chanson {name} n'écoute plus sans penser à toi ?",
                "Quel geste tendre en public {name} assume totalement ?",
                "Quel style vestimentaire te va « dangereusement bien » selon {name} ?",
                "Quelle surprise du soir {name} adorerait trouver ?",
                "Quelle danse à deux {name} voudrait apprendre ?",
                "Quel moment de ta préparation {name} trouve le plus charmant ?",
                "Quelle attention du matin fait fondre {name} ?",
                "Quel serait le menu d'un dîner de séduction selon {name} ?",
                "Quel trait de ton caractère {name} trouve irrésistible ?",
                "Quel endroit rêvé pour un baiser inoubliable selon {name} ?",
                "Quel accessoire (montre, parfum, rouge à lèvres...) te rend inoubliable pour {name} ?",
                "Quelle promesse chuchotée ferait frissonner {name} ?",
                "Quel week-end improvisé ferait céder {name} sans hésiter ?",
                "Quelle complicité silencieuse {name} préfère ?",
                "Quel message codé rien qu'à vous {name} inventerait ?",
                "Quelle photo de vous deux {name} trouve la plus charmante ?",
                "Les préparatifs, le dîner ou la fin de soirée : que préfère {name} ?",
                "Quelle voix tu prends qui amuse (et charme) {name} ?",
                "Quel pari perdu {name} honorerait avec le sourire ?",
                "Quelle ambiance musicale {name} choisirait pour un dîner à deux ?",
                "Quel compliment {name} te fait dans sa tête sans le dire ?",
                "Quel passage d'une lettre d'amour {name} lirait deux fois ?",
                "Quel geste galant touche {name} plus qu'{il|elle} ne l'admet ?",
                "Quelle idée de rendez-vous à distance {name} trouve la plus séduisante ?",
                "Quelle petite jalousie {name} trouve flatteuse ?",
                "À quel moment {name} a pensé « {p:il|elle} me plaît vraiment » ?",
                "Quel fou rire complice {name} trouve secrètement charmant ?",
            ],
        ],
        'piment' => [
            'label' => 'Piment',
            'icon' => 'pepper',
            'desc'  => 'Pour pimenter votre vie de couple (réservé aux adultes consentants)',
            'questions' => [
                'Quel fantasme {name} aimerait réaliser avec toi ?',
                'Quelle partie de ton corps {name} pourrait embrasser pendant des heures ?',
                'Quel est le moment le plus torride que {name} ait vécu avec toi ?',
                'Quelle nouveauté {name} aimerait tester au lit ?',
                'Quel endroit (hors de la chambre) fait fantasmer {name} pour un moment coquin ?',
                'Douche à deux ou massage aux huiles : que choisirait {name} ?',
                'Quel message brûlant {name} rêverait de recevoir de toi en pleine journée ?',
                'Quelle tenue {name} rêve secrètement de te voir porter... ou enlever ?',
                'Yeux bandés ou lumières allumées : que préfère {name} ?',
                "Combien de temps {name} tiendrait au jeu « interdit de se toucher » ?",
                "Quel mot doux (ou pas si doux) {name} adore entendre dans l'intimité ?",
                'Sur une échelle de 1 à 10, à quel point {name} est {joueur|joueuse} sous la couette ?',
                'Quel souvenir pimenté {name} repasse en boucle dans sa tête ?',
                'Matin câlin ou nuit blanche : le moment préféré de {name} ?',
                'Quel accessoire {name} oserait ajouter à vos jeux ?',
                'Si vous jouiez un jeu de rôle coquin, quel duo choisirait {name} ?',
                "Qu'est-ce que {name} n'a jamais osé te demander ?",
                'Quelle promesse pimentée {name} veut te faire pour vos prochaines retrouvailles ?',
                'Quel serait le programme du week-end 100 % piment rêvé de {name} ?',
                'Préliminaires interminables ou passion express : la préférence de {name} ?',
                'Quel endroit de ton corps {name} trouve le plus envoûtant ?',
                "Quelle chanson {name} mettrait pour une soirée qui monte en température ?",
                'Qui de vous deux craque en premier après un regard qui en dit long, selon {name} ?',
                'Quel gage coquin {name} aimerait te donner... et lequel aimerait-{il|elle} recevoir ?',
                "Quel moment de la journée {name} trouve le plus propice aux jeux amoureux ?",
                "Quelle pièce de la maison fait le plus fantasmer {name} ?",
                "Quel type de massage {name} préfère donner... et recevoir ?",
                "Quelle règle {name} instaurerait pour un week-end sans sortir du lit ?",
                "Quel vêtement {name} trouve le plus troublant à enlever ?",
                "Quelle gourmandise {name} partagerait autrement qu'à table ?",
                "Quel jeu de cartes coquin {name} inventerait ?",
                "Quelle heure de la nuit inspire le plus {name} ?",
                "Quelle scène de film {name} rejouerait volontiers avec toi ?",
                "Au jeu du « on attend encore un peu », combien de temps tient {name} ?",
                "Quelle phrase chuchotée à l'oreille fait de l'effet à {name} ?",
                "Bungalow isolé ou suite avec vue : le décor qui inspire {name} ?",
                "Quel accessoire vestimentaire {name} te laisserait choisir ?",
                "Quelle découverte récente a le plus plu à {name} ?",
                "Quel moment d'improvisation {name} a préféré ?",
                "Quelle mise en scène {name} préparerait pour te surprendre ?",
                "Quel gage {name} n'oserait donner qu'à toi ?",
                "Nuque, dos ou épaules : la zone préférée de {name} ?",
                "Quel parfum d'huile de massage {name} choisirait ?",
                "Quelle chanson {name} mettrait en fond d'une soirée très privée ?",
                "Quel « interdit » amusant {name} instaurerait le temps d'une soirée ?",
                "Quelle surprise {name} glisserait dans la valise d'un week-end ?",
                "Quel jeu de regards {name} gagne à tous les coups ?",
                "Nuit d'été torride ou hiver sous la couette : la préférence de {name} ?",
                "Quel petit-déjeuner {name} choisirait après une longue nuit ?",
                "Quel niveau de lumière {name} trouve idéal ?",
                "Quel message {name} aimerait recevoir à minuit ?",
                "Quelle danse privée {name} oserait... ou rêverait de recevoir ?",
                "Douche à deux : express ou interminable pour {name} ?",
                "Surprendre ou se laisser surprendre : le rôle préféré de {name} ?",
                "Tendresse, humour ou audace : quelle carte {name} joue en premier ?",
                "Les retrouvailles ou les au revoir qui s'éternisent : le plus intense pour {name} ?",
                "Quel coin du salon a une histoire secrète selon {name} ?",
                "Quelle boisson {name} partagerait dans un seul verre ?",
                "Spa privatif ou cabane perdue : le week-end rêvé de {name} ?",
                "Quelle caresse du bout des doigts fait frissonner {name} ?",
                "Quel mot {name} trouve le plus sensuel de la langue française ?",
                "Quelle heure {name} trouve la plus belle pour ne pas dormir ?",
                "Comment {name} pimenterait un « vérité ou gage » ?",
                "Quelle mise en beauté {name} ferait rien que pour toi ?",
                "Quel silence à deux {name} trouve le plus éloquent ?",
                "Quelle saison donne le plus d'idées à {name} ?",
                "Film à frissons ou frissons sans film : le programme de {name} ?",
                "Combien de bougies {name} allumerait pour l'ambiance parfaite ?",
                "Quelle promesse {name} glisserait dans un au revoir ?",
                "Quel compliment osé {name} rêve de te faire ?",
                "Quelle tenue de nuit {name} préfère... quand il y en a une ?",
                "Quel moment entre vous {name} a trouvé le plus inattendu ?",
                "L'ouïe, le toucher ou le goût : quel sens {name} aiguiserait en premier ?",
                "Paris, Rome ou une île déserte pour une nuit de folie : le choix de {name} ?",
                "Doux, relevé ou explosif : quel niveau de piment assume {name} ?",
                "Quelle photo restée entre vous {name} garde précieusement ?",
                "Quel rendez-vous « comme des inconnus » {name} aimerait jouer ?",
                "Quelle limite {name} aimerait repousser tout doucement ?",
                "Quel massage de 5 minutes {name} transformerait volontiers en une heure ?",
                "Quel coin de la maison n'a « pas encore d'histoire » selon {name} ?",
                "Quelle sonnerie discrète {name} choisirait pour vos messages privés ?",
                "Quel dessert {name} trouve le plus suggestif ?",
                "Quelle position de câlin {name} préfère pour s'endormir ?",
                "Café au lit ou câlin prolongé : le réveil préféré de {name} ?",
                "Quelle audace vestimentaire {name} oserait pour te surprendre ?",
                "Inconnus au bar ou retrouvailles secrètes : le jeu de rôle qui amuserait {name} ?",
                "Quelle zone sous-estimée {name} défendrait : les mains, la nuque ou les poignets ?",
                "Quel code secret {name} inventerait pour dire « ce soir » ?",
                "Quelle chanson lente {name} trouve dangereusement efficace ?",
                "Écharpe, plaid ou chocolat chaud : quel accessoire d'hiver {name} détournerait ?",
                "Quelle réplique culte {name} trouve terriblement sexy ?",
                "Ascenseur, cuisine ou voiture : le moment volé préféré de {name} ?",
                "Quelle durée {name} donnerait aux préliminaires parfaits ?",
                "Quel souvenir {name} classerait « top 3 » sans hésiter ?",
                "Quelle surprise à minuit {name} tenterait ?",
                "Quel « menu » {name} composerait pour une soirée spéciale : entrée, plat, dessert ?",
                "Quelle façon de dire « viens là » {name} trouve irrésistible ?",
                "Quel pari {name} proposerait, dont le gage reste... à négocier ?",
                "Quelle lettre très privée {name} oserait t'écrire ?",
                "Complice et câlin ou taquin et joueur : le lendemain matin préféré de {name} ?",
            ],
        ],
    ];

    /**
     * Packs du mode « Faire connaissance » : les DEUX joueurs répondent à la
     * même question sur eux-mêmes, puis les réponses se dévoilent côte à côte.
     * Formulation à la deuxième personne ; les accords {a|b} suivent le sexe
     * du joueur qui lit la question.
     */
    public const DISCOVER_PACKS = [
        'premiers_pas' => [
            'label' => 'Premiers pas',
            'icon'  => 'sprout',
            'desc'  => 'Les bases pour briser la glace',
            'questions' => [
                'Quel est ton plat préféré ?',
                'Plutôt lève-tôt ou couche-tard ?',
                'Quelle musique tourne en boucle chez toi en ce moment ?',
                'Ton film ou ta série doudou ?',
                'Ton week-end idéal, il ressemble à quoi ?',
                'Thé, café ou chocolat chaud ?',
                'Quel pays rêves-tu de visiter ?',
                'Plutôt mer, montagne ou grande ville ?',
                'Quel est ton petit plaisir du quotidien ?',
                'Sucré ou salé ?',
                'Quel sport ou quelle activité te fait du bien ?',
                'As-tu un talent caché ?',
                'Ton animal préféré (et pourquoi) ?',
                'Quelle est ta saison préférée ?',
                'Ton emoji le plus utilisé ?',
                'Plutôt soirée entre amis ou tête-à-tête tranquille ?',
                'Quel plat cuisines-tu le mieux ?',
                'Ta madeleine de Proust (une odeur, un plat, une chanson...) ?',
                "Le dernier truc qui t'a fait beaucoup rire ?",
                'Ton endroit préféré dans ta ville ?',
                'Quel métier rêvais-tu de faire enfant ?',
                'Cinéma, resto ou balade pour un premier rendez-vous ?',
                'Quelle appli occupe le plus ton téléphone ?',
                "Si tu gagnais un billet d'avion demain, tu pars où ?",
                "Quelle est ta couleur préférée ?",
                "Tu écoutes quoi en voiture ?",
                "Ton dessert préféré ?",
                "Plutôt chien ou chat ?",
                "Ta pizza idéale, elle a quoi dessus ?",
                "Quel super-pouvoir choisirais-tu ?",
                "Ton jeu de société préféré ?",
                "La ville où tu te sens le mieux ?",
                "Ton émission ou podcast du moment ?",
                "Plutôt petit-déjeuner salé ou sucré ?",
                "Quel est ton mois préféré de l'année ?",
                "Tu as grandi où ?",
                "C'était quoi, ton premier concert ?",
                "Quelle langue aimerais-tu parler ?",
                "Plutôt lecture, jeux vidéo ou séries le soir ?",
                "Quel plat te rappelle ton enfance ?",
                "Tu es du matin ou du soir pour être efficace ?",
                "Ta boisson chaude de l'hiver ?",
                "Quel sport as-tu pratiqué enfant ?",
                "Ton dernier coup de cœur (film, livre, musique) ?",
                "Plutôt plage ou piscine ?",
                "Quelle est ta fête préférée de l'année ?",
                "Tu cuisines quoi quand tu veux te faire plaisir ?",
                "Quel animal te fait craquer ?",
                "Midi, aprem ou soir : ton créneau idéal pour un rendez-vous ?",
                "Quelle matière tu préférais à l'école ?",
                "Plutôt appels ou messages ?",
                "Quelle appli tu recommandes à tout le monde ?",
                "Ton endroit préféré pour te détendre ?",
                "Quel est le dernier pays que tu as visité ?",
                "Tu regardes quoi quand tu ne sais pas quoi regarder ?",
                "Plutôt matin pressé ou matin tranquille ?",
                "Quel bruit tu trouves apaisant ?",
                "Ta météo préférée ?",
                "Italien, asiatique, africain : ton restaurant type ?",
                "Tu chantes quoi sous la douche ?",
                "Plutôt week-end organisé ou improvisé ?",
                "Quel talent aimerais-tu avoir ?",
                "Ton fruit préféré ?",
                "Ta fête d'anniversaire la plus mémorable ?",
                "Plutôt marche, vélo ou transports ?",
                "Quel est ton magasin préféré ?",
                "Tu es plutôt {ponctuel|ponctuelle} ou toujours cinq minutes en retard ?",
                "Quelle série as-tu regardée plusieurs fois ?",
                "Au restaurant : toujours le même plat ou découverte ?",
                "Quel est ton parfum de glace ?",
                "Plutôt montagne l'hiver ou plage l'été ?",
                "Quelle musique te met de bonne humeur direct ?",
                "Tu préfères offrir ou recevoir des cadeaux ?",
                "Quel est ton créneau de sieste idéal ?",
                "Plutôt cuisine maison ou livraison ?",
                "Quel réseau social utilises-tu le plus ?",
                "Été léger ou hiver cocooning : ta garde-robe préférée ?",
                "C'était quoi, ton dernier fou rire ?",
                "Tu collectionnes (ou as collectionné) quoi ?",
                "Plutôt film au cinéma ou sur le canapé ?",
                "Quelle est ta spécialité au karaoké ?",
                "Quel plat rates-tu à chaque fois ?",
                "Tu bois ton café ou ton thé comment ?",
                "Quelle heure est « trop tôt » pour toi le week-end ?",
                "Grande fête ou petit comité pour ton anniversaire ?",
                "Quel est le prochain pays sur ta liste ?",
                "Tu as un porte-bonheur ?",
                "Quelle odeur te met de bonne humeur ?",
                "Plutôt jeux d'adresse ou jeux de réflexion ?",
                "Quel est ton moyen de transport préféré en voyage ?",
                "Ta pièce préférée de la maison ?",
                "Quel est ton snack de cinéma ?",
                "Tu préfères l'aube ou le coucher de soleil ?",
                "Quel instrument aimerais-tu savoir jouer ?",
                "Plutôt marché du dimanche ou grasse matinée ?",
                "Quelle est la première chose que tu fais en rentrant chez toi ?",
                "Quel est ton emoji préféré à recevoir ?",
                "Plutôt notes vocales ou grands pavés écrits ?",
                "Quel petit truc rend ta journée meilleure ?",
                "Ton plat réconfort des soirs de flemme ?",
            ],
        ],
        'plus_perso' => [
            'label' => 'Plus perso',
            'icon'  => 'compass',
            'desc'  => 'Valeurs, rêves et petites histoires',
            'questions' => [
                "Qu'est-ce qui te rend vraiment {heureux|heureuse} ?",
                'De quoi es-tu le plus {fier|fière} ?',
                'Quelle valeur est non négociable pour toi ?',
                'Quel rêve aimerais-tu réaliser dans les cinq ans ?',
                "Qu'est-ce qui te fait le plus peur en amour ?",
                'Ton enfance en trois mots ?',
                "Quelle personne t'inspire le plus ?",
                "Qu'est-ce que les gens devinent rarement sur toi ?",
                'Plutôt cœur qui parle ou tête qui décide ?',
                "Quelle leçon la vie t'a-t-elle apprise récemment ?",
                "Qu'est-ce qui te met vraiment en colère ?",
                "Ta définition d'une belle histoire d'amour ?",
                'Grande tablée ou petit cocon : tu te vois comment plus tard ?',
                'Quel moment de ta vie referais-tu volontiers ?',
                'Qu\'est-ce qui te redonne le moral les jours gris ?',
                'Quelle habitude aimerais-tu changer ?',
                "Quel genre d'attention te touche le plus ?",
                "Quel compliment t'a le plus {touché|touchée} ?",
                "Qu'attends-tu d'une relation ?",
                "Ton plus grand fou rire, c'était quand ?",
                'Si tu pouvais poser une question à ton futur, ce serait laquelle ?',
                'Quelle chanson raconte un bout de ta vie ?',
                "Qu'est-ce qui te rend {curieux|curieuse} en ce moment ?",
                'Quel est ton refuge quand ça ne va pas ?',
                "Qu'est-ce qui te donne de l'énergie au quotidien ?",
                "Quel événement a changé ta façon de voir la vie ?",
                "Quelle est ta plus belle amitié, et pourquoi elle dure ?",
                "Tu te ressources plutôt {seul|seule} ou {entouré|entourée} ?",
                "Quel âge te correspond le mieux dans ta tête ?",
                "Quelle cause te tient à cœur ?",
                "Quel serait ton lieu de vie idéal dans dix ans ?",
                "Qu'est-ce que tu pardonnes difficilement ?",
                "Quelle est ta plus grande qualité selon tes proches ?",
                "Quel défaut assumes-tu complètement ?",
                "Qu'est-ce qui te fait te sentir {vivant|vivante} ?",
                "Quelle décision difficile as-tu prise récemment ?",
                "Tu crois au destin ou aux coïncidences ?",
                "Quelle relation as-tu avec ta famille ?",
                "Qu'est-ce qui te rassure quand tout va mal ?",
                "Quel conseil donnerais-tu à ton toi de 15 ans ?",
                "Quelle est ta définition de la réussite ?",
                "Que représente l'argent pour toi ?",
                "Quelle peur as-tu déjà surmontée ?",
                "Tu exprimes plutôt tes émotions ou tu les gardes ?",
                "Quel rôle joue l'amitié dans ta vie amoureuse ?",
                "Quelle est la chose la plus folle que tu aies faite par amour ?",
                "Qu'est-ce qui te rend {fier|fière} de ta famille ?",
                "Quel moment de solitude apprécies-tu le plus ?",
                "Quelle habitude prends-tu soin de garder ?",
                "Qu'est-ce qui te touche chez les autres ?",
                "Quelle est ta plus grande contradiction ?",
                "Tu préfères avoir raison ou avoir la paix ?",
                "Quel souvenir te fait sourire à coup sûr ?",
                "Qu'aimerais-tu qu'on retienne de toi ?",
                "Quelle épreuve t'a {rendu|rendue} plus {fort|forte} ?",
                "Pressé ou contemplatif : quel est ton rapport au temps ?",
                "Quelle tradition familiale veux-tu transmettre ?",
                "Qu'est-ce qui t'émerveille encore comme un enfant ?",
                "Quelle question détestes-tu qu'on te pose ?",
                "Quel livre ou film a changé quelque chose en toi ?",
                "Tu pries, tu médites, ou ni l'un ni l'autre ?",
                "Quelle est ta plus belle réussite invisible aux yeux des autres ?",
                "Que fais-tu quand tu n'arrives pas à dormir ?",
                "Quelle personne aimerais-tu remercier davantage ?",
                "Sans contrainte d'argent, quel métier ferait vibrer ton cœur ?",
                "Qu'as-tu arrêté de faire qui te manque ?",
                "Quelle est la limite que tu ne franchiras jamais ?",
                "Les disputes : tu gères à chaud ou après réflexion ?",
                "Quel compliment as-tu du mal à accepter ?",
                "Qu'apprends-tu en ce moment, sur toi ou sur la vie ?",
                "Quelle habitude des autres t'inspire ?",
                "Tu te confies facilement ou il faut te mériter ?",
                "Ton dimanche parfait, sans aucune obligation ?",
                "Quelle part d'enfance as-tu gardée ?",
                "Qu'est-ce que tu ignorais sur la vie de couple avant d'en vivre une ?",
                "Quel geste de gentillesse t'a {marqué|marquée} ?",
                "Accro ou {détaché|détachée} : ta relation avec ton téléphone ?",
                "Qu'est-ce qui te fait pleurer (film, musique, souvenir) ?",
                "Quelle promesse t'es-tu faite à toi-même ?",
                "Quel échec t'a finalement rendu service ?",
                "Mots, gestes, temps ou cadeaux : comment exprimes-tu ton affection ?",
                "Quelle journée de ta vie revivrais-tu à l'identique ?",
                "Qu'attends-tu d'un « chez nous » ?",
                "Quelle habitude matinale aimerais-tu instaurer ?",
                "Qu'est-ce qui te fait te sentir en sécurité avec quelqu'un ?",
                "Sur quel sujet pourrais-tu débattre pendant des heures ?",
                "Quelle est la chose la plus difficile que tu aies pardonnée ?",
                "Comment envisages-tu les enfants dans ta vie ?",
                "Quel lieu te fait te sentir chez toi instantanément ?",
                "Quelle version de toi préfères-tu : aujourd'hui ou il y a cinq ans ?",
                "Que fais-tu mieux que la plupart des gens ?",
                "Quelle émotion as-tu du mal à montrer ?",
                "Quel rêve d'enfant as-tu déjà réalisé ?",
                "Qu'est-ce qui te donne confiance en l'avenir ?",
                "Quelle rencontre a changé ta vie ?",
                "Comment veux-tu vieillir ?",
                "Quelle chose toute simple te paraît un luxe ?",
                "Que ferais-tu si tu étais sûr(e) de ne pas échouer ?",
                "Quel malentendu sur toi aimerais-tu corriger ?",
                "Qu'espères-tu qu'on vivra ensemble un jour ?",
            ],
        ],
        'flirt' => [
            'label' => 'Flirt',
            'icon'  => 'zap',
            'desc'  => 'Séduction légère et compliments',
            'questions' => [
                "Qu'est-ce qui t'a {attiré|attirée} en premier chez moi ?",
                'Plutôt regards appuyés ou petites attentions ?',
                'Quel compliment fait mouche à tous les coups avec toi ?',
                "C'est quoi ton premier rendez-vous idéal ?",
                "Qu'est-ce qui te fait craquer chez quelqu'un ?",
                'Plutôt messages enflammés ou appels interminables ?',
                'Quelle est ta technique (secrète) de séduction ?',
                'Le geste romantique qui te ferait fondre ?',
                "Qu'est-ce que tu remarques en premier chez quelqu'un ?",
                'Slow, rock ou pas de danse du tout ?',
                'Ton point faible quand on veut te faire rougir ?',
                'Une soirée parfaite à deux, ça ressemble à quoi ?',
                "Tu préfères qu'on te dise « tu es {beau|belle} » ou « tu es {brillant|brillante} » ?",
                "Quel surnom aimerais-tu qu'on te donne ?",
                "C'est quoi ton signe qui montre que quelqu'un te plaît ?",
                'Le détail qui te rend {fou|folle} chez quelqu\'un ?',
                'Plutôt surprise organisée ou improvisation totale ?',
                "Quelle chanson te met dans l'ambiance pour séduire ?",
                'Premier baiser : tu préfères le provoquer ou le laisser venir ?',
                "Qu'est-ce qui t'intimide chez quelqu'un qui te plaît ?",
                "Ton idée d'un rendez-vous original ?",
                'Sur une échelle de 1 à 10, tu te donnes combien en drague ?',
                "Une escapade surprise : tu m'emmènes où ?",
                "Qu'est-ce que tu aimerais que je sache sur toi ?",
                "Sourire, regard ou voix : ton faible ?",
                "Tu préfères faire le premier pas ou qu'on le fasse ?",
                "Quelle tenue te donne confiance en toi ?",
                "Quel rendez-vous éviterais-tu à tout prix ?",
                "Tu rougis facilement ?",
                "Quelle attention te fait sourire toute la journée ?",
                "Plutôt dîner aux chandelles ou street food à deux ?",
                "Quel message te donnerait envie de répondre à 2 h du matin ?",
                "Ton meilleur souvenir de premier rendez-vous ?",
                "Tu crois au coup de foudre ?",
                "Quelle question aimerais-tu que je te pose ?",
                "Quel compliment m'as-tu déjà fait... dans ta tête ?",
                "Plutôt cinéma dans le noir ou balade sous les étoiles ?",
                "Quelle chanson m'enverrais-tu pour me faire comprendre un truc ?",
                "Quel détail chez moi as-tu remarqué en premier ?",
                "Tu préfères les surprises ou tout savoir à l'avance ?",
                "Ton plan drague le plus raté (et le plus drôle) ?",
                "Quelle est la chose la plus romantique qu'on ait faite pour toi ?",
                "Tu gardes les messages importants ?",
                "Ce serait quoi, notre premier voyage idéal ?",
                "Plutôt danser toute la nuit ou parler jusqu'au matin ?",
                "Quel surnom tu ne veux SURTOUT pas qu'on te donne ?",
                "Ta définition d'un bon baiser ?",
                "Tu préfères qu'on te découvre vite ou petit à petit ?",
                "Quel emoji de ma part te ferait sourire bêtement ?",
                "Quelle activité à deux te ferait dire oui direct ?",
                "C'est quoi ton green flag absolu ?",
                "Et ton red flag rédhibitoire ?",
                "Quelle heure est parfaite pour un premier appel ?",
                "Tu penses quoi des couples qui s'habillent pareil ?",
                "Quel film voudrais-tu qu'on regarde ensemble en premier ?",
                "Plutôt taquineries ou compliments ?",
                "La plus belle chose qu'on puisse te dire au réveil ?",
                "Tu montres vite tes sentiments ou tu testes d'abord ?",
                "Ton cadeau « petit mais parfait », ce serait quoi ?",
                "Quelle chanson te donne envie de tomber {amoureux|amoureuse} ?",
                "Tu préfères l'humour ou le mystère chez quelqu'un ?",
                "Ce serait quoi, notre premier resto ?",
                "Qu'est-ce qui te ferait rater ton arrêt en pensant à quelqu'un ?",
                "Plutôt main dans la main ou bras dessus bras dessous ?",
                "Quelle météo est idéale pour un rendez-vous selon toi ?",
                "Quel talent chez quelqu'un te bluffe instantanément ?",
                "Tu écris des brouillons avant un message important ?",
                "Quelle serait ta réaction si je débarquais par surprise ?",
                "À quel moment de la journée penses-tu le plus à moi ?",
                "Plutôt {jaloux|jalouse} {discret|discrète} ou pas du tout ?",
                "Quelle chanson mettrais-tu pour notre premier slow ?",
                "Qu'est-ce qui te fait craquer dans une voix ?",
                "Tu préfères recevoir des fleurs ou un bon repas ?",
                "Le pire endroit pour un premier baiser ?",
                "Et le meilleur ?",
                "Quelle qualité te fait oublier tous les défauts ?",
                "Tu te renseignes un peu avant un rendez-vous, ou pas du tout ?",
                "Quel compliment t'a {laissé|laissée} sans voix ?",
                "Plutôt rendez-vous courts et fréquents ou longs et rares ?",
                "Qu'est-ce que tu remarques dans un sourire ?",
                "Quelle attention à distance te toucherait le plus ?",
                "Bonne nuit par message ou par appel ?",
                "Quel jeu à deux te tenterait pour un rendez-vous original ?",
                "Qu'est-ce qui rend une conversation inoubliable pour toi ?",
                "Quel parfum te fait tourner la tête ?",
                "Tu crois aux âmes sœurs ?",
                "Ce serait quoi, la playlist de nos débuts ?",
                "Quel geste anodin trouves-tu hyper charmant ?",
                "Plutôt photos de nous partout ou souvenirs rien qu'à nous ?",
                "Quelle phrase est ta meilleure arme de séduction ?",
                "Qu'est-ce qui te ferait dire oui à un deuxième rendez-vous ?",
                "Quel moment gênant te ferait rire plutôt que fuir ?",
                "Tu préfères séduire en cuisinant, en dansant ou en discutant ?",
                "Quelle est la limite à ne pas franchir en drague ?",
                "À quel signe voit-on que tu es sous le charme ?",
                "Plutôt « on se dit tout » ou « on garde du mystère » ?",
                "Quelle destination me proposerais-tu pour nous perdre un week-end ?",
                "Qu'espères-tu que je te demande bientôt ?",
                "Quel petit défaut trouves-tu craquant ?",
                "À quel moment t'es-tu dit « ça pourrait devenir sérieux » ?",
            ],
        ],
    ];

    // Questions du jour : chacun répond pour soi, les réponses se dévoilent
    // quand les deux ont répondu. Les accords {a|b} suivent le sexe du lecteur.
    public const DAILY = [
        'Quel moment de ta journée aurais-tu aimé partager avec moi ?',
        "Qu'est-ce qui t'a fait sourire aujourd'hui ?",
        'Si on était ensemble ce soir, on ferait quoi ?',
        'Quelle est la petite victoire de ta journée ?',
        "Qu'est-ce qui t'a le plus manqué chez moi aujourd'hui ?",
        "Raconte un détail de ta journée que tu ne m'aurais pas dit sinon.",
        'Quelle musique a accompagné ta journée ?',
        'De quoi as-tu besoin ce soir : réconfort, rires ou silence à deux ?',
        "Quel plat aurais-tu voulu qu'on cuisine ensemble ce soir ?",
        'Si tu pouvais te téléporter près de moi 10 minutes, ce serait pour faire quoi ?',
        "Quelle pensée pour nous deux as-tu eue aujourd'hui ?",
        "Qu'attends-tu le plus de nos prochaines retrouvailles ?",
        'Quel a été le moment le plus difficile de ta journée ?',
        'Décris le câlin dont tu aurais besoin là, tout de suite.',
        "Quelle chose as-tu apprise aujourd'hui ?",
        "Sur une échelle de 1 à 10, ton niveau d'énergie aujourd'hui... et pourquoi ?",
        'Quel rêve (la nuit) as-tu fait récemment ?',
        "Que ferais-tu si j'apparaissais à ta porte maintenant ?",
        "Quelle habitude à deux voudrais-tu qu'on crée ?",
        'Cite trois choses pour lesquelles tu es {reconnaissant|reconnaissante} aujourd\'hui.',
        "Quel souvenir de nous t'a traversé l'esprit récemment ?",
        "Qu'aimerais-tu qu'on planifie ensemble ?",
        'Si ta journée était un titre de film, ce serait quoi ?',
        'Quelle est ta météo intérieure aujourd\'hui ?',
        "Qu'est-ce que j'ai fait récemment qui t'a fait plaisir ?",
        'Quelle question aimerais-tu que je te pose plus souvent ?',
        "Qu'est-ce qui te préoccupe en ce moment ?",
        "Quel petit plaisir t'es-tu accordé aujourd'hui ?",
        'Décris ta journée en trois mots.',
        'Quelle promesse veux-tu me faire pour demain ?',
    ];

    /**
     * Rend un modèle de question : prénom + accords en genre.
     *
     * @param string $targetGender  'm' ou 'f' — joueur visé ({a|b} et {t:a|b})
     * @param string $partnerGender 'm' ou 'f' — partenaire ({p:a|b})
     */
    public static function render(string $template, string $targetName, string $targetGender, string $partnerGender = 'm'): string
    {
        $out = str_replace('{name}', $targetName, $template);

        return preg_replace_callback(
            '/\{(?:([tp]):)?([^{}|]*)\|([^{}|]*)\}/u',
            function (array $m) use ($targetGender, $partnerGender) {
                $gender = ($m[1] === 'p') ? $partnerGender : $targetGender;

                return $gender === 'f' ? $m[3] : $m[2];
            },
            $out
        );
    }

    /** Tire $n questions au hasard dans un pack (sans doublon). */
    public static function pick(string $pack, int $n, string $mode = 'guess'): array
    {
        $bank = $mode === 'discover' ? self::DISCOVER_PACKS : self::PACKS;
        $pool = $bank[$pack]['questions'] ?? reset($bank)['questions'];
        shuffle($pool);

        return array_slice($pool, 0, min($n, count($pool)));
    }

    /**
     * Question du jour déterministe : avance d'une question par jour
     * depuis la création du salon, sans répétition avant épuisement.
     */
    public static function dailyFor(Room $room, string $day): string
    {
        $start = CarbonImmutable::parse($room->created_at)->startOfDay();
        $index = max(0, $start->diffInDays(CarbonImmutable::parse($day)->startOfDay()));

        return self::DAILY[(int) $index % count(self::DAILY)];
    }

    /** Liste des packs pour l'interface. */
    public static function packList(): array
    {
        return self::toList(self::PACKS);
    }

    /** Liste des packs du mode « Faire connaissance ». */
    public static function discoverPackList(): array
    {
        return self::toList(self::DISCOVER_PACKS);
    }

    private static function toList(array $bank): array
    {
        return collect($bank)->map(fn ($pack, $id) => [
            'id'    => $id,
            'label' => $pack['label'],
            'icon'  => $pack['icon'],
            'desc'  => $pack['desc'],
        ])->values()->all();
    }
}
